# Generated by Django 4.2.1 on 2023-05-13 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField()),
                ('section_info', models.CharField(max_length=20)),
                ('days_and_times', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('room', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osu_id', models.IntegerField()),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('osu_id',), name='unique_term_osu_id'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_term_name'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.department'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_department_name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('short_name',), name='unique_department_short_name'),
        ),
        migrations.AddField(
            model_name='course_term',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.course'),
        ),
        migrations.AddField(
            model_name='course_term',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.term'),
        ),
        migrations.AddField(
            model_name='course_section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.course'),
        ),
        migrations.AddField(
            model_name='course_section',
            name='instructors',
            field=models.ManyToManyField(to='search.instructor'),
        ),
        migrations.AddField(
            model_name='course_section',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.term'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.department'),
        ),
        migrations.AddConstraint(
            model_name='instructor',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'department'), name='unique_instructor_first_last_department'),
        ),
        migrations.AddConstraint(
            model_name='course_term',
            constraint=models.UniqueConstraint(fields=('term', 'course'), name='unique_course_term'),
        ),
        migrations.AddConstraint(
            model_name='course_section',
            constraint=models.UniqueConstraint(fields=('term', 'section_id'), name='unique_term_section_id'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('department', 'number'), name='unique_course_department_number'),
        ),
    ]
