# Generated by Django 4.2.1 on 2023-05-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_course_section_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='terms',
            field=models.ManyToManyField(to='search.term'),
        ),
        migrations.DeleteModel(
            name='Course_Term',
        ),
    ]
