# Generated by Django 4.2.1 on 2023-05-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_course_terms_delete_course_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
