# Generated by Django 4.2.1 on 2023-05-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_section',
            name='days_and_times',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='section_info',
            field=models.CharField(max_length=50),
        ),
    ]
