# Generated by Django 4.2.1 on 2023-05-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_course_section_days_and_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_section',
            name='days_and_times',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='room',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='section_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
