# Generated by Django 4.2.1 on 2024-03-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_course_section_days_and_times_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(null=True)),
                ('function_name', models.TextField(null=True)),
                ('additional_info', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='course_section',
            name='barrett_data_json',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='course_section',
            name='link_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='display_boolean',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='availability',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='days_and_times',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='room',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='section_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course_section',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddConstraint(
            model_name='course_section',
            constraint=models.UniqueConstraint(fields=('term', 'course', 'link_number'), name='unique_term_course_link_number'),
        ),
    ]
