# Generated by Django 4.2.1 on 2024-03-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_error_logs_course_section_barrett_data_json_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course_section',
            name='unique_term_course_link_number',
        ),
    ]
