# Generated by Django 4.2.1 on 2024-03-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_remove_course_section_unique_term_course_link_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Error_Logs',
            new_name='Error_Log',
        ),
    ]
