# Generated by Django 4.2.1 on 2024-08-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_search_query_rename_error_logs_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_section',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course_section',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
